# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 02:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('average', models.IntegerField(default=None)),
                ('max_salary', models.IntegerField(default=None)),
                ('min_salary', models.IntegerField(default=None)),
                ('date', models.DateField(default=datetime.datetime(2017, 11, 19, 2, 58, 45, 812801))),
            ],
        ),
        migrations.CreateModel(
            name='Job_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('employed', models.CharField(blank=True, choices=[('yes', '\u5728\u8077'), ('no', '\u7121\u696d')], default='no', max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('types', models.CharField(blank=True, choices=[('full_time', '\u5168\u8077'), ('part_time', '\u517c\u8077(\u542b\u6253\u5de5)'), ('interm', '\u5be6\u7fd2'), ('temporary', '\u81e8\u6642\u5de5'), ('contract', '\u7d04\u8058\u96c7'), ('deliver', '\u6d3e\u9063')], default='full_time', max_length=100)),
                ('sex', models.CharField(blank=True, choices=[('0', '\u8acb\u9078\u64c7'), ('male', '\u7537'), ('female', '\u5973'), ('other', '\u5176\u4ed6')], default='male', max_length=100)),
                ('salary_type', models.CharField(blank='True', choices=[('0', '\u8acb\u9078\u64c7'), ('1', '\u5e74\u85aa'), ('2', '\u6708\u85aa'), ('3', '\u65e5\u85aa'), ('4', '\u6642\u85aa')], default='1', max_length=10)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('experience', models.CharField(blank=True, choices=[('0', '\u8acb\u9078\u64c7'), ('1', '1\u5e74\u6216\u4ee5\u4e0b'), ('2', '2\u5e74\u6216\u4ee5\u4e0b'), ('3', '3\u5e74\u6216\u4ee5\u4e0b')], default='1', max_length=100)),
                ('working_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('OT', models.CharField(choices=[('seldom', '\u7d55\u5c11'), ('sometimes', '\u5076\u723e'), ('often', '\u7d93\u5e38'), ('always', '\u5e7e\u4e4e\u6bcf\u5929')], default='seldom', max_length=100)),
                ('Overtime_pay', models.CharField(choices=[('yes', '\u6709'), ('no', '\u6c92\u6709'), ('not_sure', '\u4e0d\u77e5\u9053')], default='no', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2017, 11, 19, 2, 58, 45, 814286))),
            ],
        ),
        migrations.CreateModel(
            name='jobs_gov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('jobTitle', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('responsibility', models.TextField()),
                ('qualification', models.TextField()),
                ('treatment', models.TextField()),
                ('appNote', models.TextField()),
                ('remark', models.TextField()),
                ('category', models.CharField(max_length=10, null=True)),
                ('exported', models.BooleanField(default=False)),
                ('money', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='labor_gov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('jobTitle', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('responsibility', models.TextField()),
                ('qualification', models.TextField()),
                ('treatment', models.TextField()),
                ('appNote', models.TextField()),
                ('remark', models.TextField()),
                ('category', models.CharField(max_length=10, null=True)),
                ('exported', models.BooleanField(default=False)),
                ('money', models.CharField(blank=True, max_length=50)),
                ('working_date', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
