# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 03:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0005_auto_20171119_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 3, 33, 35, 775391)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 19, 3, 33, 35, 776757)),
        ),
    ]
