# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0011_auto_20171125_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor_gov',
            name='working_day_number_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labor_gov',
            name='working_hours_number_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 12, 3, 13, 41, 11, 171741)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 3, 13, 41, 11, 173388)),
        ),
    ]
