# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0013_auto_20171203_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor_gov',
            name='working_day_number_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labor_gov',
            name='working_hours_number_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 12, 3, 14, 18, 43, 221586)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 3, 14, 18, 43, 222896)),
        ),
    ]
