# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 05:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0014_auto_20171203_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labor_gov',
            old_name='appNote',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='labor_gov',
            old_name='qualification',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='labor_gov',
            old_name='remark',
            new_name='week_total_hour',
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 12, 16, 5, 31, 28, 508442)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 16, 5, 31, 28, 509713)),
        ),
    ]
