# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0015_auto_20171216_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 9, 9, 12, 26, 92493)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 1, 9, 9, 12, 26, 94116)),
        ),
    ]
