# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 03:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0022_auto_20180113_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor_gov',
            name='salary_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 27, 3, 18, 6, 603316)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 1, 27, 3, 18, 6, 604474)),
        ),
    ]
