# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 19:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0026_auto_20180127_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor_gov',
            name='money2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 27, 19, 41, 12, 451292)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 1, 27, 19, 41, 12, 452523)),
        ),
    ]
