# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0029_auto_20180127_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='collected_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=5)),
                ('latest_year', models.FloatField(blank=True, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('year', models.FloatField(blank=True, null=True)),
                ('week_hour', models.FloatField(blank=True, null=True)),
                ('OT_frequency', models.CharField(max_length=5)),
                ('OT_payment', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(default=datetime.datetime(2018, 2, 3, 17, 57, 25, 191680))),
                ('contract_week_hour', models.FloatField(blank=True, null=True)),
                ('salary_period', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 2, 3, 17, 57, 25, 189390)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 2, 3, 17, 57, 25, 190500)),
        ),
    ]
