# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0032_auto_20180203_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collected_data',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 2, 3, 18, 45, 59, 287302)),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 2, 3, 18, 45, 59, 284803)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 2, 3, 18, 45, 59, 286045)),
        ),
    ]
