# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 02:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0034_auto_20180203_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 4, 1, 2, 17, 23, 257231)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 1, 2, 17, 23, 258497)),
        ),
    ]
