# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 22:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0037_auto_20180406_2243'),
    ]

    operations = [
        
    ]
