# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 09:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0039_auto_20180406_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jobs_gov',
        ),
        migrations.RemoveField(
            model_name='collected_data',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job_detail',
            name='OT',
        ),
        migrations.RemoveField(
            model_name='job_detail',
            name='Overtime_pay',
        ),
        migrations.RemoveField(
            model_name='job_detail',
            name='employed',
        ),
        migrations.RemoveField(
            model_name='job_detail',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='job_detail',
            name='place',
        ),
        migrations.RemoveField(
            model_name='job_detail',
            name='position',
        ),
        migrations.RemoveField(
            model_name='job_detail',
            name='salary_type',
        ),
        migrations.RemoveField(
            model_name='job_detail',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='job_detail',
            name='types',
        ),
        migrations.RemoveField(
            model_name='job_detail',
            name='working_hour',
        ),
        migrations.AddField(
            model_name='collected_data',
            name='account_identify',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collected_data',
            name='location2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='OT_frequency',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='OT_payment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='account_identify',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='contract_week_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='gender',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='jobTitle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='job_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='latest_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='location2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='salary_period',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='time_stamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='week_total_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collected_data',
            name='OT_frequency',
            field=models.CharField(choices=[('絕少', '絕少'), ('偶爾', '偶爾'), ('經常', '經常'), ('幾乎每天', '幾乎每天')], max_length=20),
        ),
        migrations.AlterField(
            model_name='collected_data',
            name='OT_payment',
            field=models.CharField(choices=[('有', '有'), ('沒有', '沒有'), ('不知道', '不知道')], max_length=50),
        ),
        migrations.AlterField(
            model_name='collected_data',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 7, 9, 38, 32, 186419)),
        ),
        migrations.AlterField(
            model_name='collected_data',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='collected_data',
            name='gender',
            field=models.CharField(choices=[('', '性別'), ('m', '男'), ('f', '女'), ('other', '其他')], max_length=5),
        ),
        migrations.AlterField(
            model_name='collected_data',
            name='job_type',
            field=models.CharField(choices=[('', '職務型態'), ('全職', '全職'), ('兼職(含打工)', '兼職(含打工)'), ('實習', '實習'), ('臨時工', '臨時工'), ('約聘雇', '約聘雇'), ('派遣', '派遣')], max_length=50),
        ),
        migrations.AlterField(
            model_name='collected_data',
            name='time_stamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 7, 9, 38, 32, 184169)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 7, 9, 38, 32, 185151)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
