# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 22:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0047_auto_20180618_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collected_data',
            name='latest_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collected_data',
            name='year_of_working',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 18, 22, 23, 48, 844485)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 18, 22, 23, 48, 845654)),
        ),
    ]
