# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 00:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0049_auto_20180618_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labor_gov',
            old_name='money',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='labor_gov',
            old_name='money3',
            new_name='salary3',
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 19, 0, 35, 30, 845417)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 19, 0, 35, 30, 846426)),
        ),
    ]
