# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 00:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0050_auto_20180619_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collected_data',
            old_name='industry',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 19, 0, 53, 25, 683988)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 19, 0, 53, 25, 686055)),
        ),
    ]
