# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 00:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0051_auto_20180619_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collected_data',
            old_name='category',
            new_name='industry',
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 19, 0, 54, 33, 473160)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 19, 0, 54, 33, 474264)),
        ),
    ]
