# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 23:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0055_auto_20180625_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_detail',
            old_name='working_day_number_float',
            new_name='working_day_number_floa',
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 25, 23, 31, 27, 468698)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 25, 23, 31, 27, 470533)),
        ),
    ]
