# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 23:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0057_auto_20180625_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='collected_data',
            name='working_hours_number_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 25, 23, 39, 15, 481134)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 25, 23, 39, 15, 482301)),
        ),
    ]
