# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 23:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0060_auto_20180626_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='collected_data',
            name='account_identify',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='collected_data',
            name='uid',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='job_data_2.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 26, 23, 17, 47, 230790)),
        ),
    ]
