# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 00:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0061_auto_20180626_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='collected_data',
            name='salary_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 27, 0, 19, 10, 545688)),
        ),
    ]
