# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 00:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data_2', '0064_auto_20180627_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 27, 0, 38, 3, 847711)),
        ),
    ]
